version: "3.9"

services:

  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"

  web:
    build:
      context: ../../
      dockerfile: docker/local/Dockerfile
    volumes:
      - ../../:/opt/YlabDishes/
    entrypoint: docker/local/entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
